title: "justin.karimi"
sub_title: jekhokie
description: >
    Technical Learnings and Doings
url: "https://jekhokie.github.io"
github_username: jekhokie

# build settings
markdown: kramdown

paginate: 20

collections:
    personalstream:
        output: true

# pagination settinsg
gems:
  - jekyll-paginate
  - jekyll-seo-tag
